CREATE OR ALTER PROC CREATEADDMOVIE(
	@ID INT,
	@TITLE VARCHAR(100),
	@DESC VARCHAR(MAX),
	@RATING NUMERIC (19,1),
	@IMAGE VARCHAR(MAX)
)
AS 
BEGIN
	DECLARE @ERROR VARCHAR(MAX)
	BEGIN TRY
		IF EXISTS (SELECT * FROM MOVIES WHERE ID = @ID)
		BEGIN
			UPDATE MOVIES SET ID = @ID, title = @TITLE, description = @DESC, rating = @RATING, image = @IMAGE
			WHERE ID = @ID
		END
		ELSE
		BEGIN
			INSERT INTO MOVIES
			VALUES(
				@ID,
				@TITLE,
				@DESC,
				@RATING,
				@IMAGE,
				GETDATE(),
				GETDATE()
			)
		END
	END TRY
	BEGIN CATCH
		SET @ERROR = ERROR_MESSAGE()
		RAISERROR(@ERROR, 16, 1)
	END CATCH
END

--EXEC GETDATAUSER ''

SELECT * FROM MOVIES
