CREATE OR ALTER PROC CREATEUPDATEUSER(
	@USERID VARCHAR(30),
	@NAMA VARCHAR(100),
	@NAMA_PANGGILAN VARCHAR(50)
)
AS 
BEGIN
	DECLARE @ERROR VARCHAR(MAX)
	BEGIN TRY
		IF EXISTS (SELECT * FROM data_user WHERE USERID = @USERID)
		BEGIN
			UPDATE data_user SET nama = @NAMA, nama_pangilan = @NAMA_PANGGILAN
			WHERE USERID = @USERID
		END
		ELSE
		BEGIN
			INSERT INTO data_user
			VALUES(
				@USERID,
				@USERID,
				@NAMA,
				@NAMA_PANGGILAN
			)
		END
	END TRY
	BEGIN CATCH
		SET @ERROR = ERROR_MESSAGE()
		RAISERROR(@ERROR, 16, 1)
	END CATCH
END

--EXEC GETDATAUSER ''