CREATE OR ALTER PROC GETDETAILMOVIE(
	@ID INT
)
AS 
BEGIN
	DECLARE @ERROR VARCHAR(MAX)
	BEGIN TRY
		SELECT ID, title, description, rating, image, created_at, updated_at
		FROM MOVIES
		WHERE ID = @ID OR @ID = 1
	END TRY
	BEGIN CATCH
		SET @ERROR = ERROR_MESSAGE()
		RAISERROR(@ERROR, 16, 1)
	END CATCH
END
