CREATE OR ALTER PROC GETDATAUSER(
	@ID VARCHAR(50)
)
AS 
BEGIN
	DECLARE @ERROR VARCHAR(MAX)
	BEGIN TRY
		SELECT USERID, USERNAME, NAMA, 
		NAMA_PANGILAN NAMA_PANGGILAN
		FROM DATA_USER
		WHERE USERID = @ID OR @ID = ''
	END TRY
	BEGIN CATCH
		SET @ERROR = ERROR_MESSAGE()
		RAISERROR(@ERROR, 16, 1)
	END CATCH
END

--EXEC GETDATAUSER ''